// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bilcocyuytduelgzikwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpbGNvY3l1eXRkdWVsZ3ppa3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMjQ2NTIsImV4cCI6MjA3NDYwMDY1Mn0.TjWLHSaWKb7H7I3IOsKOnni8FH-0UYekU2hslQF1ifc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);